services:
  db:
    image: postgres:16-alpine
    container_name: slotora_db
    environment:
      POSTGRES_DB: slotora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./slotora-backend
    container_name: slotora_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/slotora
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8080:8080"

  frontend:
    build: ./slotora-frontend
    container_name: slotora_frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data: